### ISSUE TITLE
Doesn't Support Chinese Language 

### ISSUE THREAD

**Issue by wbsdty331** [jonathanlermitage/tikione-steam-cleaner#10]
It doesn't support chinese. The display is not normal。
Please fix it .Thx :)

![qq 20150320213148](https://cloud.githubusercontent.com/assets/4280572/6752544/6e63c630-cf4a-11e4-8f70-81deb5489e38.jpg)

**Comment by jonathanlermitage** [comment]
Hi,
the font probably doesn't support Chinese, or I have declared a font that is not present in your system (the "Steam folder" and "Custom folders list" labels have a strange appearance).
Could you send me your language file? I'll choose a font that works.

Best regards

**Comment by wbsdty331** [comment]
Hi Joha.
Language File is here https://mega.co.nz/#!RxwCCJCK
Please Fix it.

**Comment by jonathanlermitage** [comment]
Hi,
I have uploaded a version with fonts that support Chinese. Could you try this version? => http://lermitage.biz/pub/files/TikiOneSteamCleaner20150322.exe
Thank you v. much for your contribution.
