### ISSUE TITLE
Error after scanning the entire drive

### ISSUE THREAD

**Issue by SnowGabe** [jonathanlermitage/tikione-steam-cleaner#12]
I scanned the whole C: drive and TikiOne Steam Cleaner found some redistributable packages. However, the removal process failed and it's possible that the program broke GOG Galaxy Client installation.
It's much easier to scan the whole drive, as the program supports now not only Steam games. I'm asking you to add support also for applications.

Please help me to solve this error:

"(logfile):
- Delete file: C:\Program Files (x86)\Fox\Aliens versus Predator\redist\vc\vcredist_x86.exe ... ERROR
- Delete file: C:\Program Files (x86)\LucasArts\Monkey Island 2 LeChucks Revenge Special Edition\installers\vcredist_x86.exe ... ERROR
- Delete file: C:\Program Files (x86)\MSI Afterburner\Redist\vcredist_x86.exe ... ERROR
- Delete file: C:\Program Files (x86)\RivaTuner Statistics Server\Redist\dxwebsetup.exe ... ERROR
- Delete file: C:\Program Files (x86)\RivaTuner Statistics Server\Redist\vcredist_x64.exe ... ERROR
- Delete file: C:\Program Files (x86)\RivaTuner Statistics Server\Redist\vcredist_x86.exe ... ERROR
- Delete folder: C:\Program Files\Bitdefender\Bitdefender 2015\installer ... ERROR
- Delete folder: C:\Program Files (x86)\Common Files\Adobe\Installers ... ERROR
- Delete folder: C:\Program Files (x86)\Fox\Aliens versus Predator\redist ... ERROR
- Delete folder: C:\Program Files (x86)\Fox\Aliens versus Predator\redist\directx ... ERROR
- Delete folder: C:\Program Files (x86)\LucasArts\Monkey Island 2 LeChucks Revenge Special Edition\installers ... ERROR
- Delete folder: C:\Program Files (x86)\MSI Afterburner\Redist ... ERROR
- Delete folder: C:\Program Files (x86)\MSI Afterburner\SDK\Localization\Installer ... ERROR
- Delete folder: C:\Program Files (x86)\RivaTuner Statistics Server\Redist ... ERROR
- Delete folder: C:\Program Files (x86)\RivaTuner Statistics Server\SDK\Localization\Installer ... ERROR

You saved 0.0 MB"

I'm using the latest 2.4.2 version.

**Comment by jonathanlermitage** [comment]
Hi,
Program Files folders are readonly, unless you have admin rights.
Do you launch Steam Cleaner with Admin Rights?

For the GOG Galaxy Client, could you give me more information (the detected files/folders)? I'dd add them to the default exclude list.

Best regards,

**Comment by SnowGabe** [comment]
I think Tikione didn't actually break the Galaxy Client installation, I misread the log.
I launched the program with admin rights, that solved my issue. Thank you!

I still got an error with Bitdefender though:
"- Delete folder: C:\Program Files\Bitdefender\Bitdefender 2015\installer ... ERROR"
