### ISSUE TITLE
Automatic update fails every time

### ISSUE THREAD

**Issue by Hauwertlhaufn** [jonathanlermitage/tikione-steam-cleaner#14]
When I try to use the automatic update it fails. (Windows 8.1, 32 Bit)
I also tried starting it as administrator and update it, but it fails too.

**Comment by jonathanlermitage** [comment]
Hi,
the automatic update feature has been removed since a very long time, that's why it automatic.

**Comment by Hauwertlhaufn** [comment]
Ok, thanks for this information. The change to a dialog like "Download Installer of newest version" should be less counfusing imho.

**Comment by jonathanlermitage** [comment]
Fixed, will be part of next release.
