### ISSUE TITLE
Simplified Chinese Language Files.

### ISSUE THREAD

**Issue by wbsdty331** [jonathanlermitage/tikione-steam-cleaner#17]

**Comment by wbsdty331** [comment]
![zh-cn](https://cloud.githubusercontent.com/assets/4280572/10116464/e589cfda-6468-11e5-9b51-c09749f7d471.png)
Rename png to ini

**Comment by wbsdty331** [comment]
https://drive.google.com/file/d/0B9Qm978p4Cb2RlJjRGIzaGFOcXc/view?usp=sharing
https://drive.google.com/file/d/0B9Qm978p4Cb2X3c0NXFvbW1uVVk/view?usp=sharing

Files and China Flag Image
Thanks.

**Comment by jonathanlermitage** [comment]
Hello,
thx for your contribution.

Unfortunately, I no longer work on Steam Cleaner.  
Feel free to fork the project.

Regards,
