### ISSUE TITLE
I want to Continue this Project Development.

### ISSUE THREAD

**Issue by wbsdty331** [jonathanlermitage/tikione-steam-cleaner#19]
Some People like it, So I want to Continue it
OK?

**Comment by rappo** [comment]
If you fork it, let us know. As a user I'd love to see this project stay alive.

**Comment by wbsdty331** [comment]
Yes, I fork it . on OSChina Git,(Because Github is slow speed in China.)
https://git.oschina.net/wbsdty331/Tikione-Steam-Cleaner-Plus/
Right?

**Comment by jonathanlermitage** [comment]
Good news.
If you need assistance, don't hesitate to ask questions about code or configuration.

Regards,

**Comment by wbsdty331** [comment]
https://github.com/wbsdty331/TikiOne-steam-Cleaner-Plus
This, I added some new feature.
Welcome fork
