### ISSUE TITLE
Excluding "downloading" folder?

### ISSUE THREAD

**Issue by voltagex** [jonathanlermitage/tikione-steam-cleaner#20]
Should you automagically exclude the downloading folder?

![image](https://cloud.githubusercontent.com/assets/159567/16714472/f17d0b0e-4707-11e6-94ca-5bea65cc3d31.png)

I'm not sure if this exists only while Steam is open.

**Comment by jonathanlermitage** [comment]
Good idea!  
I will protect this folder for the next release.

**Comment by cbdelavenne** [comment]
Would your enhancement cover GOG and Origin as well?

**Comment by jonathanlermitage** [comment]
Sure!
Do you know the name of the download folder/path for GOG and Origin?

**Comment by mariosumd** [comment]
GOG: C:\Program Files (x86)\GalaxyClient\Games\!Downloads
Origin: No Idea. Apparently has another folder called Origin Games where it stores the games.

**Comment by jonathanlermitage** [comment]
For GOG, are you sure about the "!" in "Games!Downloads" ?

**Comment by mariosumd** [comment]
It was copied directly from the folders browser.

**Comment by jonathanlermitage** [comment]
OK, thx :-)

**Comment by jonathanlermitage** [comment]
Verified. Will publish release 3.0.1 asap.
Closing this ticket.
