### ISSUE TITLE
Automatically detect custom path

### ISSUE THREAD

**Issue by mirh** [jonathanlermitage/tikione-steam-cleaner#24]
They are stored in `%steam%\SteamApps\libraryfolders.vdf`

Hoping of course %steam% is already automatically retrieved from either HKCU\SOFTWARE\Valve\Steam or HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Steam

**Comment by jonathanlermitage** [comment]
Thx! I'll take a look at `libraryfolders.vdf` file
