### ISSUE TITLE
Patterns are case-sensitive

### ISSUE THREAD

**Issue by mirh** [jonathanlermitage/tikione-steam-cleaner#25]
Or otherwise I can't explain why "directx_Jun2010_redist" hasn't been found.

**Comment by jonathanlermitage** [comment]
I should document this :p  
Patterns have to be lowercase (I apply lowercase to scanned paths ; see https://github.com/jonathanlermitage/tikione-steam-cleaner/blob/master/src/main/java/fr/tikione/steam/cleaner/util/FileUtils.java).

**Comment by jonathanlermitage** [comment]
Better, I'll make regex case-insensitive.

**Comment by mirh** [comment]
Oh, [btw](http://filehippo.com/download_directx/history/):

```directx_Jun2010_redist
directx_feb2010_redist
directx_aug2009_redist
directx_mar2009_redist
directx_nov2008_redist
directx_aug2008_redist
directx_jun2008_redist
directx_mar2008_redist
directx_nov2007_redist
directx_aug2007_redist
directx_jun2007_redist
directx_apr2007_redist
directx_feb2007_redist
directx_dec2006_redist
directx_oct2006_redist
directx_aug2006_redist
directx_jun2006_redist
directx_apr2006_redist
directx_feb2006_redist
directx_dec2005_redist
directx_9c_oct05sdk_redist
directx_9c_Aug05sdk_redist
directx_9c_redist
```

And then [perhaps](http://web.archive.org/web/20081216235715/http://www.microsoft.com/downloads/Browse.aspx?displaylang=en&categoryid=2)

```
DX80NTeng
DX81NTeng

**Comment by jonathanlermitage** [comment]
There is a pattern for those directx redists ;)  
See https://github.com/jonathanlermitage/tikione-steam-cleaner/blob/master/dist2/conf/backup/tikione-steam-cleaner_patterns.ini : line 44: ".*__redist(s)?$"

**Comment by jonathanlermitage** [comment]
OMG ok, there is a "__" instead of a "_" in the regex :p ....

**Comment by mirh** [comment]
Mhh, I dunno. 
There *shouldn't* be a pattern. Those are their names period. 

Besides, now that I see, it seems "directx_Jun2010_redist" is the outlier. 
I mean.. like every redist ever has always been lower cases.. But this. 

I guess its your choice.

**Comment by jonathanlermitage** [comment]
There are patterns since folders and file names may vary.

**Comment by mirh** [comment]
Then if we really want to go down into the rabbit hole, they could choose just \*any\* name. 
And then the only way to recognize them would be dxsetup] or [something](https://github.com/jonathanlermitage/tikione-steam-cleaner/issues/26#issuecomment-248240126). 

(It's starting to feel awkward how the issues interweave)

**Comment by jonathanlermitage** [comment]
patterns are now case-insensitive ; closing issue
