### ISSUE TITLE
Just look inside steamapps folders

### ISSUE THREAD

**Issue by mirh** [jonathanlermitage/tikione-steam-cleaner#27]
Especially don't waste time searching in steam html cache or screenshots.

**Comment by Luckz** [comment]
Userdata especially is a complete waste of time and should not be parsed.

**Comment by jonathanlermitage** [comment]
thx, I'll fix that asap

**Comment by jonathanlermitage** [comment]
Fixed for main Steam folder. Will reproduce it for custom path in #24
