### ISSUE TITLE
Only present redist used once

### ISSUE THREAD

**Issue by mirh** [jonathanlermitage/tikione-steam-cleaner#28]
Or at least don't _tick_ them by default (+ explanation of the reasons if user will). 

The information about this can be found under HKLM\SOFTWARE\WOW6432Node\Valve\Steam\Apps for every game. 

This prevents dumb issues with steam forever asking user to install those dependencies, in the case he had never ran the game. 

Then.. in a perfect world the perfect thing would be to check if the corresponding resource is already installed on the system, and if successful allow to delete the file and set the right DWORDs.. But I guess this is kind of complicate to implement.

**Comment by jonathanlermitage** [comment]
About HKLM\SOFTWARE\WOW6432Node\Valve\Steam\Apps: is there an easy way to predict games name?

Another solution: I can upgrade game's vdf install file in order to remove references to redist packages. It was implemented in a previous version of Steam Cleaner. Finally, I found it a little bit buggy and I removed it.

**Comment by mirh** [comment]
> is there an easy way to predict games name?

I guess check either every `HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Steam App ####` entry, or `SteamApps\appmanifest_####.acf`


> I can upgrade game's vdf install file in order to remove references to redist packages

Yes, but you really don't know if user has or not that dependency. 
Now that you mentions vdf though, I realize not every game is like ace combat (aka reg keys are created after installers success). 
In XCOM for example it's way dumber: it checks if its HKCU\SOFTWARE\Valve\Steam\Apps\#### has installed flag on 1, if not it runs all installers ==> profit.
