### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Hauwertlhaufn** [jonathanlermitage/tikione-steam-cleaner#29]
The font size is very small on a screen with a high pixel density.
Imho it would be good to have a option to change it.

**Comment by jonathanlermitage** [comment]
Ok, I will make it configurable for next release.

**Comment by jonathanlermitage** [comment]
Finally, font rendering is a pain on Java+Swing. It needs more rework than expected.  
I expect a fix for 3.0.4 release.

**Comment by jonathanlermitage** [comment]
Java 9 seems to improve font rendering. Tested with Java 9.0.4 on Windows 10 and a hdpi configuration (125% zoom factor), it's OK for me.  
I'll ship a Java 9 VM (JRE9) with 3.0.8 release.
