### ISSUE TITLE
Windows Defender seeing installer as severe threat.

### ISSUE THREAD

**Issue by PJB3005** [jonathanlermitage/tikione-steam-cleaner#38]
![](https://i.imgur.com/osXTHYp.png)

I downloaded the regular installer from the releases section.

**Comment by jonathanlermitage** [comment]
Thx for this report.  
This is very strange since I simply use an old Nullsoft Installer.  
I'll warn Microsoft about this problem.

**Comment by PJB3005** [comment]
BTW, I just tried the no JRE version, Windows Defender has no complaints with it.

**Comment by jonathanlermitage** [comment]
Yeah, I get no answer from MS :-(  
I'll no longer provide Nullsoft installer.
