### ISSUE TITLE
Block Steam from redwonloading the redists

### ISSUE THREAD

**Issue by Chaython** [jonathanlermitage/tikione-steam-cleaner#41]
This is pretty pointless; it took so long to execute; and Steam just redownloads all the redists.
This would only be useful if it automatically added symbolic links or something so steam wouldn't redownload them... :/

**Comment by jonathanlermitage** [comment]
you should not delete redistributable packages for games that are regularly updated. You can uncheck them in the redist table.

I already tested symlinks, but it's a bad idea. Some packages may have same name and different size, and Steam may show some errors.

**Comment by Chaython** [comment]
I do see steam is building a "Steamworks Shared" for redists for some games; now
%steamapps%\common\_CommonRedist
I actually noticed this a few months ago but there was only 2 in there : P so thought nothing of it
Hopefully they do this for all of their applications in the future :/
Still wish redists were optional overall

**Comment by jonathanlermitage** [comment]
Thx!  
If deleting this `common_CommonRedist` folder is a safe operation, I'll add to redist list.

**Comment by Chaython** [comment]
steamapps\common\Steamworks Shared\_CommonRedist
It's building nearly everyday; so don't add it unless you somehow block it from building

 Volume in drive C is MX300 SSD
 Volume Serial Number is DC64-01C0

 Directory of C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared\_CommonRedist

2018-12-27  03:08 AM    <DIR>          .
2018-12-27  03:08 AM    <DIR>          ..
2018-12-27  03:08 AM                10 1.bat
2018-12-27  03:08 AM                 0 1.txt
2018-11-27  05:37 PM    <DIR>          DirectX
2018-11-29  11:29 PM    <DIR>          DotNet
2018-11-29  11:29 PM    <DIR>          vcredist
2018-11-27  05:37 PM    <DIR>          XNA
               2 File(s)             10 bytes
               6 Dir(s)  244,348,768,256 bytes free

**Comment by jonathanlermitage** [comment]
Ok.  
Thx for this information.
