### ISSUE TITLE
Ability to sort columns ascending/descending?

### ISSUE THREAD

**Issue by TokenRing** [jonathanlermitage/tikione-steam-cleaner#6]
Right now in the current 2.4 version, I see column headers for Path, Size, and Type. Clicking the header makes the slight color change that Windows users associate with "resorting by that field" but right now, clicking the headers doesn't do anything. Seems to be a bug?

(I'd really like to sort by size, as of course size/disk space is the main reason why someone would want to use this wonderful little program!)

Final note: can you show us "total selected size: xxGB/xxMB" somewhere on your program? Maybe next to the "xx files, xx folders" line?

**Comment by jonathanlermitage** [comment]
Fixed in the latest commit: columns are now sortable.

**Comment by jonathanlermitage** [comment]
Added "Total selected size" feature (text appended to the "Remove selected items..." button's label, you'll see something like "Remove selected items from disk (123MB)").

Expect a release (2.4.2) on Monday.
