### ISSUE TITLE
Support for all installed games

### ISSUE THREAD

**Issue by SnowGabe** [jonathanlermitage/tikione-steam-cleaner#9]
Can you develop the program further to search for every installed game, not only Steam games?

**Comment by jonathanlermitage** [comment]
Hi,
if you know a non-Steam game that suffers or the redist packahe installers problem (Windows, or Linux/OSX), be sure I'll add support for it.
Regards,

**Comment by SnowGabe** [comment]
Every (?) GOG.com and Origin game.
Couldn't your app search from the entire hard drive?

**Comment by jonathanlermitage** [comment]
I found no redist package installers for GOG, Origin, Uplay games. That's why I don't really support them (but you still can add "Custom folders" outside of Steam games, it should work).

**Comment by SnowGabe** [comment]
Hotline Miami 2 on GOG. "__redist" folder contains over 100MB of unnecessary files.

**Comment by jonathanlermitage** [comment]
Thank you very much.
I'll add the "__redist" (and some variants) folder to the pattern list.
Release 2.4.1 comes asap.

**Comment by jonathanlermitage** [comment]
Feature implemented (you can choose every folder you want). Is integrated to the upcoming 2.4.1 release.
